import Head from 'next/head';
import styles from '@/src/styles/Home.module.scss';
import Header from './components/Header';
import pic from '@/public/img/pic.jpg';
import Image from 'next/image';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Header />
				<h1>Main</h1>
				<div className={styles.pic}>
					<Image src={pic} alt='pic' fill quality={50} />
				</div>
			</main>
		</>
	);
}
